version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
  
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
  postgres:
    image: postgres:12
    restart: unless-stopped
    # Runs image on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=

  redis:
    image: redis:alpine
    restart: unless-stopped
    # Runs image on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    volumes:
      - /data/redis:/data

  # mailhog:
  #   image: mailhog/mailhog
  #   # Runs image on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
  #   network_mode: service:app
  
volumes:
  postgres:
  redis: